version: "2.0"
services:
  web_dev:
    image: ijuniorfu/web_dev_centos6
    ports:
     - "80:80"
     - "443:443"
     - "2222:22"
    volumes:
     - /data/htdocs:/data/htdocs
     - /data/uploads:/data/uploads
     - /data/docker/conf/nginx/conf.d:/etc/nginx/conf.d
     - /data/docker/conf/nginx/nginx.conf:/etc/nginx/nginx.conf
     - /data/docker/conf/php/php.ini:/etc/php.ini
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"