version: "3.1"
services:
  redis_dev:
    image: redis:3.2
    ports:
      - "6380:6379"
    volumes:
      - ${REDIS_VOLUME_DIR}:/data
    command:
      redis-server --appendonly yes
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"