version: "3"
services:
  web_dev:
    image: ijuniorfu/alpine-nginx-php
    privileged: true
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"
      - "9527:9527"
    volumes:
      - ${HTDOCS_DIR}:/data/htdocs
      - ${CONF_DIR}/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${CONF_DIR}/nginx/conf.d:/etc/nginx/conf.d
      - ${CONF_DIR}/php/php.ini:/etc/php7/php.ini
      - ${CONF_DIR}/php/php-fpm.conf:/etc/php7/php-fpm.conf
      - ${CONF_DIR}/php/php-fpm.d:/etc/php7/php-fpm.d
      - ${CONF_DIR}/supervisor/supervisord.conf:/etc/supervisord.conf
      - ${CONF_DIR}/supervisor/supervisor.d:/etc/supervisor.d
    command:
      supervisord --nodaemon
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    networks:
      - custom_net
networks:
  custom_net:
    external:
      name: app_net